---
- name: Check if Homebrew is installed
  stat:
    path: /opt/homebrew/bin/brew
  register: homebrew_check

# /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

- name: Download Homebrew installation script
  get_url:
    url: https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh
    dest: /tmp/homebrew_install.sh
    mode: "0755"
  when: not homebrew_check.stat.exists

- name: Install Homebrew
  shell: /bin/bash /tmp/homebrew_install.sh
  when: not homebrew_check.stat.exists

- name: Clean up installation script
  file:
    path: /tmp/homebrew_install.sh
    state: absent
  when: not homebrew_check.stat.exists

- name: Install packages from Brewfile
  shell: brew bundle --file={{ ansible_env.HOME }}/Brewfile
  register: brew_bundle_result
  changed_when: brew_bundle_result.stdout != ""
