---
- name: homebrew tap
  homebrew_tap: >
    name=homebrew/core,jesseduffield/lazydocker
    state=present

- name: homebrew
  homebrew: >
    name={{ packages }} state=present
#    path=/opt/homebrew/bin
  vars:
    packages:
      # shell
      - bash
      - bash-completion@2
      - zsh
      - zsh-completions
      - ruby
      # image
      - imagemagick
      - graphicsmagick
      - graphviz
      # database
      - sqlite
      # languages
      - ruby
      - rbenv
      - ruby-build
      - go
      - python3
      - nvm 
      # ops
      - packer
      - kubernetes-cli
      # development tools
      - coreutils
      - findutils
      - git
      - gist
      - gh
      - hub
      - ghq
      - jid
      - peco
      - fzf
      - ripgrep
      - tmux
      - reattach-to-user-namespace
      - autoconf
      - automake
      - proctools
      - openssl
      - libyaml
      - readline
      - xz
      - direnv
      - ctags
      - curl
      - fswatch
      - nkf
      - tree
      - wget
      - htop-osx
      - jq
      - lv
      - mercurial
      - ngrep
      - pstree
      - pv
      - rlwrap
      - watch
      - heroku/brew/heroku
      - goreleaser
      - mysql

- name: homebrew cask necessary
  homebrew: >
    name={{ packages }} state=present
  vars:
    packages:
#     - dropbox
#     - google-chrome
     - iterm2
     - java
     - raycast
     - slack

- name: homebrew cask
  homebrew: >
    name={{ packages }} state=present
  vars:
    packages:
#      - android-studio
      - appcleaner
      - bettertouchtool
      - charles
#      - genymotion
      - google-cloud-sdk
      - imageoptim
      - jetbrains-toolbox
      - karabiner-elements
      - kindle
      - macx-youtube-downloader
      - ngrok
      - skype
      - tailscale
      - virtualbox
      - visual-studio-code
      - vagrant
      - vlc

- name: homebrew
  homebrew: >
    name={{ packages }} state=present
  vars:
    packages:
      - maven
      - gradle
