---
- name: homebrew tap
  homebrew_tap: >
    name=homebrew/core,jesseduffield/lazydocker
    state=present

- name: homebrew
  homebrew: >
    name={{ packages }} state=present
  vars:
    packages:
      # shell
      - bash
      - bash-completion@2
      - zsh
      - zsh-completions
      - ruby
      # image
      - imagemagick
      - graphicsmagick
      # database
      - sqlite
      # languages
      - ruby
      - rbenv
      - ruby-build
      - go
      - dep
      - python
      - python3
      - pyenv
      - pyenv-virtualenv
      - pyenv-virtualenvwrapper
      - pyenv-which-ext
      - nodebrew
      # ops
      - csshx
      - packer
      - kubernetes-cli
      # development tools
      - coreutils
      - findutils
      - git
      - gist
      - tig
      - hub
      - ghq
      - jid
      - peco
      - fzf
      - ripgrep
      - fasd
      - tmux
      - reattach-to-user-namespace
      - autoconf
      - automake
      - proctools
      - openssl
      - libyaml
      - readline
      - xz
      - direnv
      - ag
      - ctags
      - curl
      - fswatch
      - nkf
      - rmtrash
      - tree
      - wget
      - htop-osx
      - jq
      - lv
      - mercurial
      - ngrep
      - pstree
      - pv
      - rlwrap
      - watch
      - heroku/brew/heroku
      - docker-machine
      - goreleaser
      - lazydocker

- name: homebrew cask necessary
  homebrew_cask: >
    name={{ packages }} state=present
  vars:
    packages:
      - alfred
      - dropbox
#      - google-chrome
      - iterm2
      - java
      - homebrew/cask-versions/adoptopenjdk8
      - slack

- name: homebrew cask
  homebrew_cask: >
    name={{ packages }} state=present
  vars:
    packages:
      - android-studio
      - appcleaner
      - atom
      - authy
      - bettertouchtool
      - charles
      - contexts
      - dash
      - genymotion
      - google-drive-file-stream
      - google-cloud-sdk
      - imageoptim
      - intellij-idea
      - jetbrains-toolbox
      - karabiner-elements
      - kindle
      - licecap
      - macx-youtube-downloader
      - minikube
      - multipass
      - mysqlworkbench
      - ngrok
      - quitter
      - sequel-pro
      - skitch
      - skype
      - virtualbox
      - vagrant
      - sketch
      - slate
      - sourcetree
      - youtube-to-mp3
      - vlc

- name: homebrew
  homebrew: >
    name={{ packages }} state=present
  vars:
    packages:
      - maven
      - gradle
