---
- name: homebrew playbook
  hosts: all
#  become: yes
  roles:
    - homebrew
  tags:
    - homebrew
  environment:
    HOMEBREW_CASK_OPTS: "--appdir=/Applications"

# TODO:
# - install mac app like firefox
# - clone dotfiles
# - set osx defaults
# - install tmuxinator
# - install npm stuff
