---
- name: osx playbook
  hosts: all
  roles:
    - osx
  tags:
    - osx

- name: homebrew playbook
  hosts: all
#  become: yes
  roles:
    - homebrew
  tags:
    - homebrew
  environment:
    HOMEBREW_CASK_OPTS: "--appdir=/Applications"

# TODO:
# - clone dotfiles
# - install tmuxinator
# - install npm stuff
